version: '2'
services:
  administraciondenegocio-app:
    image: administraciondenegocio
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://administraciondenegocio-postgresql:5432/administracionDeNegocio
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  administraciondenegocio-postgresql:
    extends:
      file: postgresql.yml
      service: administraciondenegocio-postgresql
