version: '2'
services:
  administraciondenegocio-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/administracionDeNegocio/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=administracionDeNegocio
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
